# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0f1755563a5a59419002dc286caa3e2edf7ae266ad80b83cc5445b37daf1631256aab5e5e6baab906df1346ce58018267433d36f49e42d30b353ed739ef49a

test:
  secret_key_base: f1bcbc6f1ced9e6a74211d4175574b8174dc4a04e9ac499f4028941a16413389c578dcf3af0aedee0a2fe034dd1a74310652aa4b6a054cde155b53eb0a8923a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
